### PR TITLE
Ability to send additionalProperties 

### PR DESCRIPTION
**Pull request by briananderson1222**
## Changes
- Added ability to extend the s object with additionalProperties
- Cleared properties after sending event
  `npm run build`

### CODE REVIEW

**Comment by briananderson1222** [comment]
I am open to feedback here if anyone has more experience integrating with Adobe Analytics

**Comment by briananderson1222** [comment]
@carbonrobot - Hey Charlie, I would also prefer not to have to include the `s.clearVars()`. According to this documentation: https://marketing.adobe.com/resources/help/en_US/sc/implement/props_vs_eVars.html -- In the section that says `Persistence` it states that "Props do not persist beyond the image request they were fired on.". Unfortunately in practice the `prop` events I am attempting to extend onto the s Object are firing not only for my event but also for the next PageView which makes me wonder if this documentation is false. s.clearVars() (https://marketing.adobe.com/resources/help/en_US/sc/implement/function_clearVars.html) states that it will clear the `props` vars which is why I am using it here.

If you have any other suggestions I am very open to them as I too would like not to have to include that line.

**Comment by briananderson1222** [comment]
Right now, we are just trying to use prop0, prop1, prop2, etc by doing the following:

``` js
$analytics.eventTrack('SomeEvent', { prop0: 'uniqueProp0', prop1: 'uniqueProp1', prop2: 'uniqueProp2'});
```

The properties seem to get sent with the request, but then also seem to get sent with the next (and all future) pageTrack events as well. I wonder if we maybe need to set the linkTrackVars back to None instead of clearing all vars? 

I wasn't aware of clearVars only being available in the AppMeasurement framework so thanks for that heads up. I am pretty new to Adobe Analytics as a whole so it's possible I am not understanding something correctly. 

I appreciate the assistance!

**Comment by briananderson1222** [comment]
@carbonrobot - If I move the `s.clearVars()` to the top of the registerEventTrack, I don't think that'll help us with the pageTrack continuing to send these properties as they won't be cleared until the next time we call eventTrack. Any thoughts on this? I am happy to move it, but I don't think it'll solve the specific issue we are seeing.

**Comment by briananderson1222** [comment]
Unfortunately I am not seeing that in my testing which seems to directly contradict the documentation link that I sent you in regards to 'Persistence' of props vs eVars. My understanding is that the properties should only get sent for that event and not for any events or page views after that since it is a Traffic measurement. 

If that were the case I would have no issue with adding the clearVars to the top of this method, but as it is right now the props are getting sent with our next call to `pageTrack`.

Any ideas what might be going on? I may be misreading the documentation or perhaps it is just lying to me? :)

**Comment by briananderson1222** [comment]
I do see the props being sent with the event `s.tl()`. So you want clearVars both before and after?

**Comment by briananderson1222** [comment]
You know what, now that I think about it. I wonder if the request gets sent with the properties but the reporting suite is what decides whether or not to actually track it or not. I was basing this solely off of the request going out and not on what the reporting suite was actually tracking. 

Let me read up on that forum post and circle back.

Thanks for the link

**Comment by briananderson1222** [comment]
But even link tracking is sent as an 'Image Request' from what I can see so that would apply to both `s.t` and `s.tl` methods. I am very much not a fan of the clearVars solution. I think you're right in that it might be best to call before the pageTrack event only, but I still wonder about the consequences of that. 

Still reading up on that post. Cannot stress how thankful I am for your interest in this PR.

**Comment by briananderson1222** [comment]
Unfortunately I have not had any more luck with this as both `s.t` and `s.tl` both seem to send the props with the request (meaning clearVars would need to be called in both situations OR after the event tracking like I originally had it since that is the only place we allow for extending the s Object). 

I have not been able to confirm whether the analytics suite is actually tracking the properties being sent from a reporting perspective. That is what I will focus on next and get back to you. Regardless it seems like we are in agreement with the implementation minus the `s.clearVars()` part. 

I will attempt to follow back up later in the day with any discoveries I make. Thanks!

**Comment by briananderson1222** [comment]
After a little more research, while I am not sure exactly why the props get sent for multiple `s.tl` calls I think it is best to call `s.clearVars` before making pageTrack requests as I think that feature relies on page refreshes in the traditional website sense. Also, I don't think automatically including the `s.linkTrackVars` is a great idea and should be on the user that is doing the extending of the s property.

**Comment by jptinsman** [comment]
I would like to know when this feature will be merged. I could not add any additional properties unless I had this change on my version of the plugin. I would also like to found out the result of the discussion around `s.clearVars`

Also, I am new to analytics and was scraping around trying to get this plugin and angulartics to work but could not figure out why my eVars and props were not getting sent even after the change. Turns out it has to do with Adobe disabling all additional vars and events by default. Please update the documentation to include...

> In order to track additional variables and events, you must enable them. You can do this by adding the directive prefix `analytics-` to the enabling directive.
> 
> ```
> <button class="btn btn-lg" type="submit" 
>         analytics-on 
>         analytics-link-track-vars="prop1,eVar11" 
>         analytics-link-track-events="event7"
>         analytics-prop-1="my prop 1"
>         analytics-e-var-11="my eVar 11"
>         analytics-events="event7">Click Me!</button>
> ```

**Pull request merged**
